/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/Users/kalou/spice/m4-install"
#define EXEC_PREFIX "/Users/kalou/spice/m4-install"
#define BINDIR "/Users/kalou/spice/m4-install/bin"
#define SBINDIR "/Users/kalou/spice/m4-install/sbin"
#define LIBEXECDIR "/Users/kalou/spice/m4-install/libexec"
#define DATAROOTDIR "/Users/kalou/spice/m4-install/share"
#define DATADIR "/Users/kalou/spice/m4-install/share"
#define SYSCONFDIR "/Users/kalou/spice/m4-install/etc"
#define SHAREDSTATEDIR "/Users/kalou/spice/m4-install/com"
#define LOCALSTATEDIR "/Users/kalou/spice/m4-install/var"
#define RUNSTATEDIR "/Users/kalou/spice/m4-install/var/run"
#define INCLUDEDIR "/Users/kalou/spice/m4-install/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/Users/kalou/spice/m4-install/share/doc/m4"
#define INFODIR "/Users/kalou/spice/m4-install/share/info"
#define HTMLDIR "/Users/kalou/spice/m4-install/share/doc/m4"
#define DVIDIR "/Users/kalou/spice/m4-install/share/doc/m4"
#define PDFDIR "/Users/kalou/spice/m4-install/share/doc/m4"
#define PSDIR "/Users/kalou/spice/m4-install/share/doc/m4"
#define LIBDIR "/Users/kalou/spice/m4-install/lib"
#define LISPDIR "/Users/kalou/spice/m4-install/share/emacs/site-lisp"
#define LOCALEDIR "/Users/kalou/spice/m4-install/share/locale"
#define MANDIR "/Users/kalou/spice/m4-install/share/man"
#define PKGDATADIR "/Users/kalou/spice/m4-install/share/m4"
#define PKGINCLUDEDIR "/Users/kalou/spice/m4-install/include/m4"
#define PKGLIBDIR "/Users/kalou/spice/m4-install/lib/m4"
#define PKGLIBEXECDIR "/Users/kalou/spice/m4-install/libexec/m4"
