name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: find . -type d -maxdepth 1 | grep -vE 'venv|git|src|tarballs|source|install | xargs -n 1 make -C {}'
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
